# Default values for narwhal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: datappeal/narwhal
  tag: latest
  pullPolicy: Always

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

configuration:
  catalog:
    type: hive # hive | glue
    name: hive_prod
    config:
      fs.s3a.access.key: ""
      fs.s3a.secret.key: ""
      hive.metastore.uris: thrift://<hive-metastore-uri>:9083
      hive.metastore.warehouse.dir: "file:///tmp"

  tables:
    - name: test_table_00
      schema: test_schema
      params:
        file_count_threshold: 0
        target_file_size_bytes: 536870912

    - name: test_table_01
      schema: test_schema

  rewrite_files:
    enabled: true
    policy:
      type: FILE_SKEW
      params:
        target_file_size_bytes: 536870912
        file_size_skew_threshold: 0.2

    integration:
      type: SQS
      params:
        region: eu-west-1
        queue: <sqs queue url>
        batch_size: 10


extraEnv: []

cronjob:
  enabled: true
  schedule: "5 4 * * *"
  resources: { }
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }

argo:
  cronjob:
    enabled: true
    schedule: "5 4 * * *"
    resources: { }
    nodeSelector: { }
    tolerations: [ ]
    affinity: { }
