{{- if eq .Values.argo.cronjob.enabled true -}}
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name:  {{ include "narwhal.cronwf.name" . }}
spec:
  schedule: {{.Values.argo.cronjob.schedule}}
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: narwhal
    volumes:
      - name: config-volume
        configMap:
          name: {{ include "narwhal.configmap.config" . }}
    templates:
      - name: {{ .Chart.Name }}
        container:
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
          args: [ "/config/config.yml" ]
          volumeMounts:
            - mountPath: /config
              name: config-volume
{{- end }}
