{{- if eq .Values.cronjob.enabled true -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "narwhal.fullname" . }}
  labels:
  {{- include "narwhal.labels" . | nindent 4 }}
spec:
  schedule: {{.Values.cronjob.schedule}}
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: config-volume
              configMap:
                name: {{ include "narwhal.configmap.config" . }}
          containers:
            - name: {{ .Chart.Name }}
              image: {{.Values.image.repository}}:{{.Values.image.tag}}
              command:
                - "/config/config.yml"
              imagePullPolicy: {{.Values.image.pullPolicy}}
              {{- with .Values.cronjob.resources}}
              volumeMounts:
                - mountPath: /config
                  name: config-volume
              resources:
          {{- toYaml . | nindent 8}}
          {{end}}

          {{- with .Values.cronjob.nodeSelector }}
          nodeSelector:
          {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.cronjob.affinity }}
          affinity:
          {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.cronjob.tolerations }}
          tolerations:
    {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- end }}